config/routes.rb
Etsydemo::Application.routes.draw do
  

  devise_for :users
  resources :listings do
    resources :orders, only:[:new,:create]
  end

  get "pages/about"
  get "pages/contact"
  root :to => 'listings#index'

  get "seller",:to => 'listings#seller', :as => 'seller'
  get 'sales' => 'orders#sales'
  get 'purchases' => 'orders#purchases'

  

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	if Rails.env.development?
		has_attached_file :image,:styles =>{:medium => '200x', :thumb => '100x100>'},:default_url=>'default@2x.png'
	else
		has_attached_file :image,:styles =>{:medium => '200x', :thumb => '100x100>'},:default_url=>'default@2x.png',
		:storage => :dropbox,
		:dropbox_credentials => Rails.root.join('config/dropbox.yml'),
		:path => ":style/:id_:filename"
	end

   validates_presence_of(:name,:description,:price)
   validates_numericality_of(:price,:greater_than => 0)

   belongs_to :user
   has_many :orders

   default_scope order('created_at DESC')
end

app/models/order.rb
class Order < ActiveRecord::Base
	validates_presence_of :address,:city,:state

	belongs_to :listing

	belongs_to :buyer, class_name: 'User'
	belongs_to :seller, class_name: 'User'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name


  has_many :listings, dependent: :destroy
  has_many :sales, class_name: "Order",foreign_key: "seller_id"
  has_many :purchases, class_name: "Order",foreign_key: "buyer_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, :if => :devise_controller?
  helper_method :current_user?,:current_owner?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :name
  	devise_parameter_sanitizer.for(:account_update) << :name
  end

  def current_user?(listing)
	  current_user && current_user.id == listing.user_id 
  end

  alias current_owner? current_user?

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index,:show]
  before_action :correct_user, :except => [:index,:show,:new]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create

    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render action: 'show', status: :created, location: @listing }
      else
        format.html { render action: 'new' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url }
      format.json { head :no_content }
    end
  end

  def seller
    @listings = Listing.where("user_id = ?",current_user.id)
   # render('index')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price,:image)
    end

    def correct_user
      if @listing
        redirect_to(:root,alert: "You cannot modify that Listing") unless current_user.id == @listing.user_id
      end
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @listing = Listing.find(params[:listing_id])
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    listing_id = params[:listing_id]
    @listing = Listing.find(listing_id)

    @order = Order.new(order_params)
    @order.buyer_id = current_user.id
    
    @order.seller_id = @listing.user_id
    @order.listing_id = listing_id

    Stripe.api_key = ENV["STRIPE_API_KEY"]
    token = params[:stripeToken]
    begin
      charge = Stripe::Charge.create(
        :amount => (@listing.price * 100).floor,
        :currency => 'usd',
        :card => token
        )
      flash[:notice] = 'Thanks for ordering'
    rescue Stripe::CardError => e
      flash[:danger] = e.message
    end

    respond_to do |format|
      if @order.save
        format.html { redirect_to :root }
        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  def sales
    @orders = Order.where({:seller => current_user}).order('created_at desc')
  end

   def purchases
    @orders = Order.where({:buyer => current_user}).order('created_at desc')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:address, :city, :state,:listing_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/application/_header.html.erb
<div class="navbar-wrapper">


  <div class="navbar navbar-default " id="navigate" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand"  id = 'logo' href="/">Etsy Demo</a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">

          <li><a href="/pages/about">About</a></li>
          <li><a href="/pages/contact">Contact</a></li>  
        </ul>
        <% if user_signed_in? %>

        <ul class="nav navbar-nav pull-right">
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name.capitalize%> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to('My Listings', seller_path)%></li>
            <li><%= link_to('My Sales', sales_path)%></li>
            <li><%= link_to('My Purchases', purchases_path)%></li>
            <li class="divider"></li>
            <li><%= link_to('Edit Profile', edit_user_registration_path)%></li> 
            <li><%= link_to('Log Out', destroy_user_session_path, :method => 'delete')%></li>
          </ul>
          <!-- <li><%= link_to('My Listings', seller_path)%></li>  -->
           
        </ul>
        <% else %>
        <ul class="nav navbar-nav pull-right">
          <li><%= link_to('Log In', new_user_session_path)%></li> 
          <li><%= link_to('Sign Up', new_user_registration_path)%></li> 

        </ul>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Etsydemo</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "https://js.stripe.com/v2/" %>
	<%= csrf_meta_tags %>
	<%= tag 'meta', :name=> 'stripe-key',:content => ENV["STRIPE_PUBLIC_KEY"] %>
</head>
<body>
	<%= render('header') %>
	<div class = 'container'>
		<% flash.each do |name,msg| %>
    <div id ='alert'class = 'alert text-center alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>'>
      <button type='button'class ='close' data-dismiss = 'alert'>&times;</button>
      <%= msg %>
    </div>
  <% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing,:html => {:multipart => true, :class => 'form-horizontal'}) do |f| %>
  <% if @listing.errors.any? %>
  <div class = 'devise_error text-center form-group bg-danger'>
    <ul class = 'list-unstyled' >
      <% @listing.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description ,:class => 'form-control',:rows => 4 %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price,:class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image%>
  </div>
  <div class="form-group">
    <%= f.submit nil,:class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<div class = 'container'>
	<div class = 'row'>
		<div class='col-xs-3'>
         <br>
         <br>
         <br>
         <br>
         <br>
         <a href= <%= url_for(@listing)%>><%= image_tag(@listing.image.url(:medium), class:'img-responsive')%></a>

		</div>
		<div class='col-xs-6'>
			<h1 class = 'text-center'>Editing listing</h1>
			<%= render 'form' %>

			<div class = 'pull-right'>
				<%= link_to 'Show', @listing,class:'btn btn-small btn-default' %> <%= link_to 'Back', :back,class:'btn btn-small btn-default'  %>
			</div>

		</div>
		<div class='col-xs-3'></div>
	</div>
</div>

app/views/listings/index.html.erb
<div class = 'jumbotron' id = 'custom-header'>
<h1> Hand Crafted Items from around the World </h1>
<h2> Discover rare one-of-a-kind items </h2>
</div>
<div class = 'container'>
  <div class = 'row' >
    <% @listings.each do |listing| %>
    <div class = 'col-md-3'>
      <div class = 'thumbnail'>
        <a href= <%= url_for(listing)%>><%= image_tag(listing.image.url, class:'img-responsive')%></a>
        <div class ='caption'>
          <h3><%= listing.name %> </h3>
          <p>
            <%= listing.description %>
            <% if listing.user %>
            <p class = 'text-right'> <strong> Sold by <%= listing.user.name.capitalize %></strong></p>
            <% end %>
            <p class = 'lead'><%= number_to_currency listing.price %></p>

          </p>
          <p>
            <% if current_page?({:controller => "listings",:action =>'seller'}) %>
              <%= link_to 'Edit', edit_listing_path(listing),class: 'btn btn-default' %>      
              <%= link_to 'Destroy', listing,class: 'btn btn-default', method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </p>
        </div>
        
      </div>
    </div>
    <%end %>
  </div>
  <%= link_to 'New Listing', new_listing_path,class: 'btn btn-link' if current_user %>
</div>

app/views/listings/new.html.erb
<div class = 'container'>
	<div class = 'row'>
		<div class='col-xs-3'>
			<br>
			<br>
			<br>
			<br>
			<br>
			<%= image_tag(@listing.image.url(:small),width:'200px',height:'200px',class:'img-responsive')%>

		</div>
		<div class='col-xs-6'>
			<h1 class = 'text-center'>New listing</h1>
			<%= render 'form' %>

			<div class = 'pull-right'>
				<%= link_to 'Back', listings_path,class:'btn btn-small btn-default'%>
			</div>

		</div>
		<div class='col-xs-3'></div>
	</div>
</div>

app/views/listings/old_index.html.erb
<div class = 'container'>
<h1>Listings</h1>
<table class = 'table table-striped'>
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <%#TODO: Need to refactor styles on index page %>
  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td style='vertical-align: middle;'><%= image_tag listing.image.url(:medium) %></td>
        <td style='vertical-align: middle;'><%= listing.name %></td>
        <td style='vertical-align: middle;'><%= listing.description %></td>
        <td style='vertical-align: middle;'><%= listing.price %></td>
        <td style='vertical-align: middle;'><%= link_to 'Show', listing ,class: 'btn btn-link'%></td>
        <td style='vertical-align: middle;'><%= link_to 'Edit', edit_listing_path(listing),class: 'btn btn-link' %></td>
        <td style='vertical-align: middle;'><%= link_to 'Destroy', listing,class: 'btn btn-link', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Listing', new_listing_path,class: 'btn btn-link' %>
</div>
<br>

app/views/listings/seller.html.erb
<div class = 'container'>
  <h1>My Listings</h1>
  <br>
  <table class = 'table table-striped table-bordered'>
    <thead>
      <tr>
        <th class = 'text-center'>Image</th>
        <th class = 'text-center'>Name</th>
        <th class = 'text-center'>Description</th>
        <th class = 'text-center'>Price</th>
        <th></th>
      </tr>
    </thead>
    <%#TODO: Need to refactor styles on index page %>
    <tbody>
      <% @listings.each do |listing| %>
      <tr>
        <td style='vertical-align: middle;'><%= image_tag listing.image.url(:thumb) %></td>
        <td style='vertical-align: middle;'><%= listing.name %></td>
        <td style='vertical-align: middle;'><%= listing.description %></td>
        <td style='vertical-align: middle;'><%= number_to_currency listing.price %></td>
        <td style='vertical-align: middle'> 
          <div class=" center-block dropdown" style='vertical-align: middle; width:147px'>
            <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
              Manage Listing
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li role="presentation"><%= link_to 'Show', listing ,tabindex:'-1'%></li>
              <li role="presentation"><%= link_to 'Edit', edit_listing_path(listing),tabindex:'-1' %></li>
              <li role="presentation"><%= link_to 'Destroy', listing,tabindex:'-1', method: :delete, data: { confirm: 'Are you sure?' } %></li>
            </ul>
          </div>
        </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'New Listing', new_listing_path,class: 'btn btn-link' %>
  </div>
  <br>

app/views/listings/show.html.erb
<div class = 'container'>
	<div class = 'row' >
		<div class = 'col-md-6'>
			<div class ='thumbnail'>
			<%= image_tag(@listing.image.url, class:'img-responsive') %>
		</div>
		</div>
		<div class = 'col-md-6'>
			<h2><%= @listing.name %></h2>
			<p class ='lead'>
				<%= number_to_currency @listing.price %>
			</p>
			<br>
			<br>
			<p> <strong>Description</strong> </p>
			<p>
				<%= @listing.description %>
			</p>
			<br>
			<br>
			<%= button_to('Purchase Item',new_listing_order_path(@listing), class: 'btn btn-success', method:'get') unless current_owner? @listing %>
		</div>
	</div>
	<p>
		<%= link_to('Edit', edit_listing_path(@listing),class: 'btn btn-link') if current_owner?(@listing) %> |<%= link_to 'Back',:back,class: 'btn btn-link' %>
	</p>
</div>					

app/views/orders/_form.html.erb
<%= form_for([@listing,@order], :class => 'form-horizontal',:id => 'new_order') do |f| %>
<% if @order.errors.any? %>
<div class = 'devise_error text-center form-group bg-danger'>
  <ul class = 'list-unstyled' >
    <% @order.errors.full_messages.each do |msg| %>
    <li> <%= msg %> </li>
    <% end %>
  </ul>
</div>
<% end %>

<div id = 'stripe_error' class = 'alert alert-danger' style ='display:none'>
  <noscript> Javascript is not enabled.Please enable Javascript in your browser settings to continue </noscript>
</div>

<div class="form-group">
  <%= f.label :address %><br>
  <%= f.text_field :address,:class => 'form-control'  %>
</div>
<div class="form-group">
  <%= f.label :city %><br>
  <%= f.text_field :city,:class => 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :state %><br>
  <%= f.text_field :state,:class => 'form-control' %>
</div>

<div class="form-group">
  <div class = 'row'>
    <div class = 'col-md-8'>
      <%= label_tag :card_number, 'Credit Card Number' %><br>
      <%= text_field_tag :card_number,nil,{:name => nil,:'data-stripe' => 'number',:class => 'form-control'} %>
    </div>

    <div class='col-md-4'>
      <%= label_tag  :card_code, 'CVC' %><br>
      <%= text_field_tag :card_code,nil,{:name => nil,:'data-stripe' => 'cvc',:class => 'form-control'} %>
    </div>
  </div>
</div>

<div class ='form-group'>
  <div class = 'row'>
    <div class = 'col-md-8'>
      <%= select_month nil, {use_two_digit_numbers: true,:prompt => 'Expiration Month'},{:name => nil,:'data-stripe' => 'exp-month',:class => 'form-control'} %>
    </div>
    <div class='col-md-4'>
      <%= select_year nil, {start_year: Date.today.year,end_year:Date.today.year + 10,:prompt => 'Expiration Year' },{:name => nil,:'data-stripe' => 'exp-year',:class => 'form-control'} %>
    </div>
  </div>
</div>

<div class="form-group">
  <%= f.submit nil, :class => 'btn btn-primary' %>
</div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.address %></td>
        <td><%= order.city %></td>
        <td><%= order.state %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<div class = 'row'>
<div class = 'col-xs-3'>
	
						<div class = 'thumbnail'>
			<%= image_tag(@listing.image.url,class:'img-responsive')%>
		</div>
		<h4> <%= @listing.name %> </h4>
		<h4 class = 'lead'> <%= number_to_currency @listing.price %> </h4>


</div>

<div class = 'col-xs-6'>
	<%= render 'form' %>
	<%= link_to 'Cancel', :back, class:' pull-right btn btn-danger',style: 'color:white' %>
</div>

<div class = 'col-xs-3'></div>
</div>

app/views/orders/purchases.html.erb
<div class = 'container'>
<h1>My Purchases</h1>
<table class = 'table table-striped table-bordered'>
  <thead>
    <tr>
      <th>Product Name</th>
      <th> Price</th>
      <th>Seller Name/Email</th>
      <th> Order Date </th>
    </tr>
  </thead>
  <%#TODO: Need to refactor styles on index page %>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td style='vertical-align: middle;'><%= order.listing.name %></td>
        <td style='vertical-align: middle;'><%= number_to_currency order.listing.price %></td>
       
        <td style='vertical-align: middle;'><%= order.seller.name+ '/' + order.seller.email %></td>
         <td style='vertical-align: middle;'><%= order.created_at.strftime('%c') %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%#= link_to 'New Listing', new_listing_path,class: 'btn btn-link' %>
</div>
<br>

app/views/orders/sales.html.erb
<div class = 'container'>
<h1>My Sales</h1>
<table class = 'table table-striped table-bordered'>
  <thead>
    <tr>
      <th>Product Name</th>
      <th> Price</th>
      <th>Buyer Name/Email</th>
      <th> Order Date </th>
      <th>Buyer Address</th>

    </tr>
  </thead>
  <%#TODO: Need to refactor styles on index page %>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td style='vertical-align: middle;'><%= order.listing.name %></td>
        <td style='vertical-align: middle;'><%= number_to_currency order.listing.price %></td>
       
        <td style='vertical-align: middle;'><%= order.buyer.name+ '/' + order.buyer.email %></td>
         <td style='vertical-align: middle;'><%= order.created_at.strftime('%c') %></td>
        <td style='vertical-align: middle;'><%= "#{order.address}," + "#{order.city}," + "#{order.state}\n" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%#= link_to 'New Listing', new_listing_path,class: 'btn btn-link' %>
</div>
<br>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @order.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @order.state %>
</p>

<%= link_to 'Edit', edit_listing_order_path(@listing,@order) %> |
<%= link_to 'Back', orders_path %>

app/views/pages/about.html.erb
<h1> Welcome to Etsy demo </h1>
<h2> Etsydemo is an online marketplace for buying and selling items</h2>

app/views/pages/contact.html.erb
<h1> Email us at abc@etsydemo.com </h1>
<p> &copy 2013 </p>